version: 2.1

jobs:
  build:
    machine:
      image: windows-server-2019-vs2019:stable
    resource_class: windows.medium
    steps:
      - run: |
          mkdir C:\Users\circleci\volume
          echo 'Lorem ipsum.' > C:\Users\circleci\volume\tmp.txt
      - run:
          command: docker run --rm -v C:\Users\circleci\volume\:C:\data\ mcr.microsoft.com/windows:1809 dir C:\
          shell: powershell.exe
